### ISSUE TITLE
Fix The Way of Handling build.properties

### ISSUE THREAD

**Issue by ShapelessCat** [kitlangton/scala-update#43]
The file build.properties is a general properties file. Theoretically, people can add comments and properties other than `sbt.version` to it. I think for now there is no need to handle other properties (of course, they shouldn't be dropped), but the comments should be handled properly.

If we run scala-update for a project whose _build.properties_ file has the content
```
# suppress inspection "UnusedProperty" (for IntelliJ IDEA)
sbt.version=1.7.2
```
we can see an error:
```
timestamp=2022-12-11T17:08:23.687038Z level=ERROR thread=#zio-fiber-0 message="" cause="Exception in thread "zio-fiber-" scala.meta.parsers.ParseException: <input>:1: error: illegal start of definition #
# suppress inspection "UnusedProperty" (for IntelliJ IDEA)
^
	at scala.meta.internal.parsers.Reporter.syntaxError(Reporter.scala:16)"
```

Also, currently if there are other property keys in build.properties, the scala-update run can success, but the result build.properties will lose other info that was in it before updating.

With the help of the library Apache Common Configuration, I fix it. You can see my PR.

**Comment by kitlangton** [comment]
Closed by #44
